### ISSUE TITLE
Error Cannot GET /

### ISSUE THREAD

**Issue by KeJyLL** [TheSocialCode/CopyPaste.me#28]
Hi, 

I try to host 'CopyPaste' by  my own, but I finally stuck on Cannot GET /
In CopyPaste's LogFile isn't something specific. 

Some basic informations, that could help to find a solution:

NodeJS Version: v12.22.9
NPM Version: 8.5.1

npm update

      npm WARN EBADENGINE Unsupported engine {
      npm WARN EBADENGINE   package: 'babel-loader@9.1.3',
      npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
      npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
      npm WARN EBADENGINE }
      npm WARN EBADENGINE Unsupported engine {
      npm WARN EBADENGINE   package: 'node-sass@9.0.0',
      npm WARN EBADENGINE   required: { node: '>=16' },
      npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
      npm WARN EBADENGINE }
      npm WARN EBADENGINE Unsupported engine {
      npm WARN EBADENGINE   package: 'sass-loader@13.3.2',
      npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
      npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
      npm WARN EBADENGINE }
      npm WARN EBADENGINE Unsupported engine {
      npm WARN EBADENGINE   package: 'find-cache-dir@4.0.0',
      npm WARN EBADENGINE   required: { node: '>=14.16' },
      npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
      npm WARN EBADENGINE }
      npm WARN EBADENGINE Unsupported engine {
      npm WARN EBADENGINE   package: 'pkg-dir@7.0.0',
      npm WARN EBADENGINE   required: { node: '>=14.16' },
      npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
      npm WARN EBADENGINE }
      
      up to date, audited 623 packages in 45s
      
      67 packages are looking for funding
        run `npm fund` for details
      
      3 high severity vulnerabilities
      
      To address all issues (including breaking changes), run:
        npm audit fix --force
      
      Run `npm audit` for details.

npm init -y

      Wrote to /home/madmin/CopyPaste.me/package.json:
      
      {
        "name": "copypaste.me",
        "version": "1.0.0",
        "description": "Frictionless sharing between devices",
        "repository": {
          "type": "git",
          "url": "git+https://github.com/SebastianKersten/CopyPaste.me.git"
        },
        "license": "Copyright by The Social Code Repository",
        "dependencies": {
          "@fortawesome/fontawesome-free": "^6.0.0",
          "@thesocialcode/mimoto": "^1.0.2",
          "asymmetric-crypto": "^1.0.2",
          "clipboard-copy": "^4.0.1",
          "cors": "^2.8.5",
          "express": "^4.17.2",
          "file-saver": "^2.0.5",
          "fs": "0.0.1-security",
          "generate-password": "^1.7.0",
          "generate-unique-id": "^2.0.1",
          "http": "0.0.0",
          "https": "^1.0.0",
          "log-to-file": "^3.0.0",
          "mongodb": "^4.3.1",
          "qrcode-generator": "^1.4.4",
          "sharer.js": "^0.5.1",
          "socket.io": "^4.4.1",
          "socket.io-client": "^4.4.1"
        },
        "devDependencies": {
          "babel-core": "^6.26.3",
          "babel-loader": "^9.1.2",
          "clean-webpack-plugin": "^4.0.0",
          "css-loader": "^6.6.0",
          "file-loader": "^6.2.0",
          "html-loader": "^3.1.0",
          "mini-css-extract-plugin": "^2.5.3",
          "node-sass": "^9.0.0",
          "remove-files-webpack-plugin": "^1.1.3",
          "sass-loader": "^13.3.2",
          "style-loader": "^3.3.1",
          "webpack": "^5.69.0",
          "webpack-cli": "^4.9.2",
          "webpack-manifest-plugin": "^4.1.1"
        },
        "bugs": {
          "url": "https://github.com/SebastianKersten/CopyPaste.me/issues"
        },
        "homepage": "https://github.com/SebastianKersten/CopyPaste.me#readme",
        "main": "webpack.config.js",
        "scripts": {
          "test": "echo \"Error: no test specified\" && exit 1"
        },
        "keywords": [],
        "author": ""
      }

MongoDB.js added      &tls=true   (bc I use cloud version of mongoDB)

        // 7. compose
        sMongoURL += configFile.mongodb.host.toString() + ':' + configFile.mongodb.port.toString();
        if (config.mongoauthenticate) sMongoURL += '?authMechanism=SCRAM-SHA-1&authSource=' + configFile.mongodb.dbname + '&tls=true';

**Comment by gguest2021** [comment]
i get the same error :(  please help !! :(

version nodejs : 18
version mongo: 07
